name: SonarQube

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      # 3) Cache Sonar
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # 4) Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 5) Build + Test + Generate JaCoCo report (IMPORTANT)
      - name: Build and test
        run: mvn clean test jacoco:report

      # 6) Sonar analysis (after coverage is generated)
      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
